### ISSUE TITLE
when compile tensorflow so, has error.

### ISSUE THREAD

**Issue by kitterive** [jhjin/tensorflow-cpp#4]
ERROR: /home/guoxiujiang/project/tensorflow-cplus/tensorflow-cpp-master/ext/src/tensorflow-ext/third_party/gpus/cuda_configure.bzl:883:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
INFO: Elapsed time: 2.063s
make[2]: *** [ext/src/tensorflow-ext-stamp/tensorflow-ext-build] 错误 1
make[1]: *** [CMakeFiles/tensorflow-ext.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by jhjin** [comment]
You might want to check your Bazel version according to this thread  https://github.com/tensorflow/tensorflow/issues/8619 or find a better solution in tensorflow repo since it looks like a compilation issue.
