### ISSUE TITLE
After compile ,I run the app, read graph error:

### ISSUE THREAD

**Issue by kitterive** [jhjin/tensorflow-cpp#5]
guoxiujiang@kedaxtb:~/project/tensorflow-cplus/tensorflow-cpp-master$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib
guoxiujiang@kedaxtb:~/project/tensorflow-cplus/tensorflow-cpp-master$ CUDA_VISIBLE_DEVICES=0
guoxiujiang@kedaxtb:~/project/tensorflow-cplus/tensorflow-cpp-master$ ./app ./data/grace_hopper.jpg
2017-04-18 15:32:53.726598: E app.cc:91] Read proto
guoxiujiang@kedaxtb:~/project/tensorflow-cplus/tensorflow-cpp-master$ ./app ./data/grace_hopper.jpg
2017-04-18 15:35:18.156560: E app.cc:91] Read proto
guoxiujiang@kedaxtb:~/project/tensorflow-cplus/tensorflow-cpp-master$ 

but the file "tensorflow_inception_graph.pb" is there.

**Comment by jhjin** [comment]
It is unclear to spot a problem based on the information. If it is not able to find the file, you can try with an absolute path of the file. It might help.

**Comment by kitterive** [comment]
Thanks for your reply,

It is not the problem of pb file path , it is can't read model file correctly : if (!ReadBinaryProto(tensorflow::Env::Default(), graph_path, &graph_def).ok()) {
    LOG(ERROR) << "Read proto";
    return -1;
  }

This is my compile steps, am I right?  
1  I use "make dependency" command install dependency;
2  use  "cmake ./",  It will generate a Makefile, but it will override you project file
3 I use "make"  compile the thensorflow lib
4 I use your project Makefile override cmake genenated  Makefile, 
5  "make app" generated app executable file
6 "make run"   run the test app

**Comment by jhjin** [comment]
There's no override of Makefile. Tensorflow will be built under `./build` separately. (Check this out. https://github.com/jhjin/tensorflow-cpp/blob/master/Makefile#L16-L17 ) `make` is equivalent to the sequence of commands `make build` `make data` `make app` `make run`. So 2 and 4 sound incorrect.

**Comment by kitterive** [comment]
Thanks
