### ISSUE TITLE
I am wondering is there are any way to use this in Window10?

### ISSUE THREAD

**Issue by spk921** [jhjin/tensorflow-cpp#6]
Thank you for sharing example code. 
Currently, I am working with Unity to run Oculus which only run under Window os. 
Does this code run under Window? Or do you have any example pointer urls or references? 
Thank you.

**Comment by jhjin** [comment]
You need to build *.dll to do the same thing on Windows, which seems to be doable according to the thread https://github.com/tensorflow/tensorflow/issues/18 although I haven't tried it out.

**Comment by spk921** [comment]
Thanks. I know there is C# wrapper. Thinking three methods. 1. .dll and use api from it. 2. Use C# wrapper. 3. Use IronPython for unity python binding.
